// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llravell/go-shortener/internal/usecase (interfaces: URLRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/llravell/go-shortener/internal/entity"
)

// MockURLRepo is a mock of URLRepo interface.
type MockURLRepo struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepoMockRecorder
}

// MockURLRepoMockRecorder is the mock recorder for MockURLRepo.
type MockURLRepoMockRecorder struct {
	mock *MockURLRepo
}

// NewMockURLRepo creates a new mock instance.
func NewMockURLRepo(ctrl *gomock.Controller) *MockURLRepo {
	mock := &MockURLRepo{ctrl: ctrl}
	mock.recorder = &MockURLRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepo) EXPECT() *MockURLRepoMockRecorder {
	return m.recorder
}

// DeleteMultipleURLs mocks base method.
func (m *MockURLRepo) DeleteMultipleURLs(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultipleURLs", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultipleURLs indicates an expected call of DeleteMultipleURLs.
func (mr *MockURLRepoMockRecorder) DeleteMultipleURLs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultipleURLs", reflect.TypeOf((*MockURLRepo)(nil).DeleteMultipleURLs), arg0, arg1, arg2)
}

// GetURL mocks base method.
func (m *MockURLRepo) GetURL(arg0 context.Context, arg1 string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", arg0, arg1)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockURLRepoMockRecorder) GetURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockURLRepo)(nil).GetURL), arg0, arg1)
}

// GetUserURLS mocks base method.
func (m *MockURLRepo) GetUserURLS(arg0 context.Context, arg1 string) ([]*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLS", arg0, arg1)
	ret0, _ := ret[0].([]*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLS indicates an expected call of GetUserURLS.
func (mr *MockURLRepoMockRecorder) GetUserURLS(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLS", reflect.TypeOf((*MockURLRepo)(nil).GetUserURLS), arg0, arg1)
}

// Store mocks base method.
func (m *MockURLRepo) Store(arg0 context.Context, arg1 *entity.URL) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockURLRepoMockRecorder) Store(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockURLRepo)(nil).Store), arg0, arg1)
}

// StoreMultipleURLs mocks base method.
func (m *MockURLRepo) StoreMultipleURLs(arg0 context.Context, arg1 []*entity.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMultipleURLs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMultipleURLs indicates an expected call of StoreMultipleURLs.
func (mr *MockURLRepoMockRecorder) StoreMultipleURLs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMultipleURLs", reflect.TypeOf((*MockURLRepo)(nil).StoreMultipleURLs), arg0, arg1)
}
