// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llravell/go-shortener/internal/usecase (interfaces: HashGenerator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHashGenerator is a mock of HashGenerator interface.
type MockHashGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockHashGeneratorMockRecorder
}

// MockHashGeneratorMockRecorder is the mock recorder for MockHashGenerator.
type MockHashGeneratorMockRecorder struct {
	mock *MockHashGenerator
}

// NewMockHashGenerator creates a new mock instance.
func NewMockHashGenerator(ctrl *gomock.Controller) *MockHashGenerator {
	mock := &MockHashGenerator{ctrl: ctrl}
	mock.recorder = &MockHashGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashGenerator) EXPECT() *MockHashGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockHashGenerator) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockHashGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockHashGenerator)(nil).Generate))
}
