linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exportloopref

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
