linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exportloopref
    - gochecknoglobals
    - reassign
    - exhaustruct
    - tagliatelle
    - wrapcheck
    - varnamelen
    - testpackage
    - funlen
    - paralleltest
    - noctx
    - ireturn
    - testifylint

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd

  gosec:
    excludes:
      - G115
      - G404
      - G114
